// Every country a node can be in, keyed by the ISO 3166-1 code flag-icons names its
// flag by. The node feed (api.sentnodes.com) sends a country NAME, never a code, and
// its spelling is its own ("Congo (DRC)", "Ivory Coast", "Turkey"), so a name is
// resolved through every spelling the common sources use: the feed itself, ISO,
// flag-icons, CLDR (what Intl.DisplayNames says), MaxMind/ipinfo, IP2Location's
// "Korea (Republic of)" forms, and the Natural Earth abbreviations the world map
// file uses ("Dem. Rep. Congo", "Bosnia and Herz."). The flags and the maps both
// look countries up here, so a country the feed starts reporting tomorrow has its
// flag and its place on the map already. The second column is the name shown when
// only the code is known; for every country the feed reported on 2026-10-10 it is
// the feed's own spelling.
//
// Spellings are compared after key(): case, accents, punctuation, "&"/"and",
// "St."/"Saint" and "the" do not matter, so only spellings that differ in their
// words are listed.
const COUNTRIES: readonly (readonly string[])[] = [
  ['af', 'Afghanistan'],
  ['ax', 'Aland Islands', 'Åland'],
  ['al', 'Albania'],
  ['dz', 'Algeria'],
  ['as', 'American Samoa'],
  ['ad', 'Andorra'],
  ['ao', 'Angola'],
  ['ai', 'Anguilla'],
  ['aq', 'Antarctica'],
  ['ag', 'Antigua and Barbuda'],
  ['ar', 'Argentina'],
  ['am', 'Armenia'],
  ['aw', 'Aruba'],
  ['au', 'Australia'],
  ['at', 'Austria'],
  ['az', 'Azerbaijan'],
  ['bs', 'Bahamas'],
  ['bh', 'Bahrain'],
  ['bd', 'Bangladesh'],
  ['bb', 'Barbados'],
  ['by', 'Belarus'],
  ['be', 'Belgium'],
  ['bz', 'Belize'],
  ['bj', 'Benin'],
  ['bm', 'Bermuda'],
  ['bt', 'Bhutan'],
  ['bo', 'Bolivia', 'Bolivia, Plurinational State of'],
  ['bq', 'Caribbean Netherlands', 'Bonaire, Sint Eustatius and Saba', 'Bonaire'],
  ['ba', 'Bosnia and Herzegovina', 'Bosnia and Herz.', 'Bosnia'],
  ['bw', 'Botswana'],
  ['bv', 'Bouvet Island'],
  ['br', 'Brazil'],
  ['io', 'British Indian Ocean Territory'],
  ['vg', 'British Virgin Islands', 'Virgin Islands (British)'],
  ['bn', 'Brunei', 'Brunei Darussalam'],
  ['bg', 'Bulgaria'],
  ['bf', 'Burkina Faso'],
  ['bi', 'Burundi'],
  ['kh', 'Cambodia'],
  ['cm', 'Cameroon'],
  ['ca', 'Canada'],
  ['cv', 'Cape Verde', 'Cabo Verde'],
  ['ky', 'Cayman Islands'],
  ['cf', 'Central African Republic', 'Central African Rep.'],
  ['td', 'Chad'],
  ['cl', 'Chile'],
  ['cn', 'China'],
  ['cx', 'Christmas Island'],
  ['cc', 'Cocos (Keeling) Islands', 'Cocos Islands', 'Keeling Islands'],
  ['co', 'Colombia'],
  ['km', 'Comoros'],
  ['cd', 'Congo (DRC)', 'DR Congo', 'DRC', 'Democratic Republic of the Congo', 'Dem. Rep. Congo',
    'Congo, The Democratic Republic of the', 'Congo - Kinshasa', 'Zaire'],
  ['cg', 'Republic of the Congo', 'Congo', 'Congo Republic', 'Congo - Brazzaville'],
  ['ck', 'Cook Islands'],
  ['cr', 'Costa Rica'],
  ['hr', 'Croatia'],
  ['cu', 'Cuba'],
  ['cw', 'Curaçao'],
  ['cy', 'Cyprus'],
  ['cz', 'Czech Republic', 'Czechia'],
  ['dk', 'Denmark'],
  ['dj', 'Djibouti'],
  ['dm', 'Dominica'],
  ['do', 'Dominican Republic', 'Dominican Rep.'],
  ['ec', 'Ecuador'],
  ['eg', 'Egypt'],
  ['sv', 'El Salvador'],
  ['gq', 'Equatorial Guinea', 'Eq. Guinea'],
  ['er', 'Eritrea'],
  ['ee', 'Estonia'],
  ['sz', 'Eswatini', 'Swaziland'],
  ['et', 'Ethiopia'],
  ['fk', 'Falkland Islands', 'Falkland Is.', 'Falkland Islands (Malvinas)'],
  ['fo', 'Faroe Islands', 'Faeroe Islands'],
  ['fj', 'Fiji'],
  ['fi', 'Finland'],
  ['fr', 'France'],
  ['gf', 'French Guiana'],
  ['pf', 'French Polynesia'],
  ['tf', 'French Southern Territories', 'Fr. S. Antarctic Lands', 'French Southern and Antarctic Lands'],
  ['ga', 'Gabon'],
  ['gm', 'Gambia'],
  ['ge', 'Georgia'],
  ['de', 'Germany'],
  ['gh', 'Ghana'],
  ['gi', 'Gibraltar'],
  ['gr', 'Greece'],
  ['gl', 'Greenland'],
  ['gd', 'Grenada'],
  ['gp', 'Guadeloupe'],
  ['gu', 'Guam'],
  ['gt', 'Guatemala'],
  ['gg', 'Guernsey'],
  ['gn', 'Guinea'],
  ['gw', 'Guinea-Bissau'],
  ['gy', 'Guyana'],
  ['ht', 'Haiti'],
  ['hm', 'Heard Island and McDonald Islands', 'Heard & McDonald Islands'],
  ['hn', 'Honduras'],
  ['hk', 'Hong Kong', 'Hong Kong SAR China', 'Hong Kong SAR'],
  ['hu', 'Hungary'],
  ['is', 'Iceland'],
  ['in', 'India'],
  ['id', 'Indonesia'],
  ['ir', 'Iran', 'Iran, Islamic Republic of'],
  ['iq', 'Iraq'],
  ['ie', 'Ireland'],
  ['im', 'Isle of Man'],
  ['il', 'Israel'],
  ['it', 'Italy'],
  ['ci', 'Ivory Coast', "Côte d'Ivoire"],
  ['jm', 'Jamaica'],
  ['jp', 'Japan'],
  ['je', 'Jersey'],
  ['jo', 'Jordan', 'Hashemite Kingdom of Jordan'],
  ['kz', 'Kazakhstan'],
  ['ke', 'Kenya'],
  ['ki', 'Kiribati'],
  ['xk', 'Kosovo'],
  ['kw', 'Kuwait'],
  ['kg', 'Kyrgyzstan'],
  ['la', 'Laos', "Lao People's Democratic Republic", 'Lao PDR'],
  ['lv', 'Latvia'],
  ['lb', 'Lebanon'],
  ['ls', 'Lesotho'],
  ['lr', 'Liberia'],
  ['ly', 'Libya'],
  ['li', 'Liechtenstein'],
  ['lt', 'Lithuania', 'Republic of Lithuania'],
  ['lu', 'Luxembourg'],
  ['mo', 'Macau', 'Macao', 'Macao SAR China', 'Macau SAR'],
  ['mg', 'Madagascar'],
  ['mw', 'Malawi'],
  ['my', 'Malaysia'],
  ['mv', 'Maldives'],
  ['ml', 'Mali'],
  ['mt', 'Malta'],
  ['mh', 'Marshall Islands'],
  ['mq', 'Martinique'],
  ['mr', 'Mauritania'],
  ['mu', 'Mauritius'],
  ['yt', 'Mayotte'],
  ['mx', 'Mexico'],
  ['fm', 'Micronesia', 'Federated States of Micronesia', 'Micronesia, Federated States of'],
  ['md', 'Moldova', 'Republic of Moldova', 'Moldova, Republic of'],
  ['mc', 'Monaco'],
  ['mn', 'Mongolia'],
  ['me', 'Montenegro'],
  ['ms', 'Montserrat'],
  ['ma', 'Morocco'],
  ['mz', 'Mozambique'],
  ['mm', 'Myanmar', 'Myanmar (Burma)', 'Burma'],
  ['na', 'Namibia'],
  ['nr', 'Nauru'],
  ['np', 'Nepal'],
  ['nl', 'Netherlands', 'Netherlands (Kingdom of the)', 'Holland'],
  ['nc', 'New Caledonia'],
  ['nz', 'New Zealand'],
  ['ni', 'Nicaragua'],
  ['ne', 'Niger'],
  ['ng', 'Nigeria'],
  ['nu', 'Niue'],
  ['nf', 'Norfolk Island'],
  ['kp', 'North Korea', "Korea, Democratic People's Republic of", "Democratic People's Republic of Korea"],
  ['mk', 'North Macedonia', 'Macedonia', 'Republic of North Macedonia',
    'Macedonia, The Former Yugoslav Republic of'],
  ['mp', 'Northern Mariana Islands'],
  ['no', 'Norway'],
  ['om', 'Oman'],
  ['pk', 'Pakistan'],
  ['pw', 'Palau'],
  ['ps', 'Palestine', 'State of Palestine', 'Palestine, State of', 'Palestinian Territories',
    'Palestinian Territory'],
  ['pa', 'Panama'],
  ['pg', 'Papua New Guinea'],
  ['py', 'Paraguay'],
  ['pe', 'Peru'],
  ['ph', 'Philippines'],
  ['pn', 'Pitcairn Islands', 'Pitcairn'],
  ['pl', 'Poland'],
  ['pt', 'Portugal'],
  ['pr', 'Puerto Rico'],
  ['qa', 'Qatar'],
  ['re', 'Réunion'],
  ['ro', 'Romania'],
  ['ru', 'Russia', 'Russian Federation'],
  ['rw', 'Rwanda'],
  ['bl', 'Saint Barthélemy'],
  ['sh', 'Saint Helena', 'Saint Helena, Ascension and Tristan da Cunha'],
  ['kn', 'Saint Kitts and Nevis'],
  ['lc', 'Saint Lucia'],
  ['mf', 'Saint Martin', 'Saint Martin (French part)'],
  ['pm', 'Saint Pierre and Miquelon'],
  ['vc', 'Saint Vincent and the Grenadines'],
  ['ws', 'Samoa'],
  ['sm', 'San Marino'],
  ['st', 'Sao Tome and Principe'],
  ['sa', 'Saudi Arabia'],
  ['sn', 'Senegal'],
  ['rs', 'Serbia'],
  ['sc', 'Seychelles'],
  ['sl', 'Sierra Leone'],
  ['sg', 'Singapore'],
  ['sx', 'Sint Maarten', 'Sint Maarten (Dutch part)'],
  ['sk', 'Slovakia'],
  ['si', 'Slovenia'],
  ['sb', 'Solomon Islands', 'Solomon Is.'],
  ['so', 'Somalia'],
  ['za', 'South Africa'],
  ['gs', 'South Georgia and the South Sandwich Islands'],
  ['kr', 'South Korea', 'Korea', 'Korea, Republic of', 'Republic of Korea'],
  ['ss', 'South Sudan', 'S. Sudan'],
  ['es', 'Spain'],
  ['lk', 'Sri Lanka'],
  ['sd', 'Sudan'],
  ['sr', 'Suriname'],
  ['sj', 'Svalbard and Jan Mayen'],
  ['se', 'Sweden'],
  ['ch', 'Switzerland'],
  ['sy', 'Syria', 'Syrian Arab Republic'],
  ['tw', 'Taiwan', 'Taiwan, Province of China'],
  ['tj', 'Tajikistan'],
  ['tz', 'Tanzania', 'Tanzania, United Republic of', 'United Republic of Tanzania'],
  ['th', 'Thailand'],
  ['tl', 'Timor-Leste', 'East Timor'],
  ['tg', 'Togo'],
  ['tk', 'Tokelau'],
  ['to', 'Tonga'],
  ['tt', 'Trinidad and Tobago'],
  ['tn', 'Tunisia'],
  ['tr', 'Turkey', 'Türkiye'],
  ['tm', 'Turkmenistan'],
  ['tc', 'Turks and Caicos Islands'],
  ['tv', 'Tuvalu'],
  ['vi', 'U.S. Virgin Islands', 'US Virgin Islands', 'Virgin Islands (U.S.)', 'United States Virgin Islands'],
  ['ug', 'Uganda'],
  ['ua', 'Ukraine'],
  ['ae', 'United Arab Emirates', 'UAE'],
  ['gb', 'United Kingdom', 'UK', 'Great Britain',
    'United Kingdom of Great Britain and Northern Ireland'],
  ['us', 'United States', 'United States of America', 'USA'],
  ['um', 'U.S. Outlying Islands', 'United States Minor Outlying Islands', 'U.S. Minor Outlying Islands'],
  ['uy', 'Uruguay'],
  ['uz', 'Uzbekistan'],
  ['vu', 'Vanuatu'],
  ['va', 'Vatican City', 'Holy See', 'Holy See (Vatican City State)'],
  ['ve', 'Venezuela', 'Venezuela, Bolivarian Republic of'],
  ['vn', 'Vietnam', 'Viet Nam'],
  ['wf', 'Wallis and Futuna'],
  ['eh', 'Western Sahara', 'W. Sahara'],
  ['ye', 'Yemen'],
  ['zm', 'Zambia'],
  ['zw', 'Zimbabwe'],
]

function key(name: string): string {
  return name
    .normalize('NFD').replace(/[̀-ͯ]/g, '')
    .toLowerCase()
    .replace(/&/g, ' and ')
    .replace(/\bst\b/g, 'saint')
    .replace(/\bthe\b/g, ' ')
    .replace(/[^a-z0-9]+/g, ' ')
    .trim()
}

const CODE_BY_KEY = new Map(COUNTRIES.flatMap(([code, ...names]) => names.map((n) => [key(n), code] as const)))
const NAME_BY_CODE = new Map(COUNTRIES.map(([code, name]) => [code, name]))

/** The flag-icons code for a country name in any spelling above, or undefined (no country, or one not listed). */
export function countryCode(name: string): string | undefined {
  return CODE_BY_KEY.get(key(name))
}

/** The name shown for a code: the second column above. */
export function countryName(code: string): string | undefined {
  return NAME_BY_CODE.get(code)
}

/**
 * The code for a polygon in the world map file, or '' for the two that are no ISO
 * country (Natural Earth's "N. Cyprus" and "Somaliland"). The maps match a polygon to
 * the nodes' countries by this code, never by name. Matching by name needed a second
 * table of renames, which was wrong for the feed: it turned the file's "Turkey" into a
 * "Türkiye" the feed does not send, so 144 nodes in Turkey were left off the globe
 * until 2026-10-10.
 */
export function polyCode(feature: { properties?: { name?: string } }): string {
  return countryCode(feature.properties?.name ?? '') ?? ''
}
